### ISSUE TITLE
after maven  build  sucess  and  run demo.HelloWorld2  demo.ForbiddenFile2  all fail

### ISSUE THREAD

**Issue by char1st** [parttimenerd/hello-ebpf#27]
show error is  libbpf: elf: skipping unrecognized data section(6) .rodata.str1.1.
and use  llvm-objdump -s -j .rodata.str1.1  found  the data is string in java code  and call BPFJ.bpf_trace_printk. 

os kernel-release is 6.5.0-41-generic .
libbpf version is 1:0.5.0-1ubuntu22.04.1:amd64

Looks like libbpf: elf: skipping unrecognized data section(6) .rodata.str1.1. is just a warning 
The error  at me.bechberger.ebpf.bpf.raw.Lib_1.bpf_object__load .
/tmp/bpf16240375866294408426.o  is demo.HelloWorld2 elf

But  I used 
bpftool prog load /tmp/bpf16240375866294408426.o  /sys/fs/bpf/test type raw_tracepoint
bpftool prog run pinned /sys/fs/bpf/test repeat 0
and 
bpftool prog tracelog can see the bpf_trace_printk the out put 

[hs_err_pid3314.log](https://github.com/user-attachments/files/16746867/hs_err_pid3314.log)

**Comment by parttimenerd** [comment]
Can you give me more information on your system and your run code?

**Comment by char1st** [comment]
[hs_err_pid3314.log](https://github.com/user-attachments/files/16746867/hs_err_pid3314.log) has some info . 
pasted  some I thought usefull 


`Command Line: --enable-native-access=ALL-UNNAMED me.bechberger.ebpf.samples.demo.HelloWorld2`

Host: Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz, 4 cores, 15G, Ubuntu 22.04.2 LTS
Time: Mon Aug 26 09:11:02 2024 UTC elapsed time: 1.095198 seconds (0d 0h 0m 1s)


```
Stack: [0x00007bedd8a2b000,0x00007bedd8b2b000],  sp=0x00007bedd8b28e00,  free space=1015k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libbpf.so.0.5.0+0x1fced]  bpf_object__load_xattr+0x4d
j  java.lang.invoke.LambdaForm$MH+0x00007bed570d2800.invoke(Ljava/lang/Object;JJ)I+10 java.base@22.0.2
j  java.lang.invoke.LambdaForm$MH+0x00007bed570d5800.invokeExact_MT(Ljava/lang/Object;JJLjava/lang/Object;)I+21 java.base@22.0.2
j  jdk.internal.foreign.abi.DowncallStub+0x00007bed570d2c00.invoke(Ljava/lang/foreign/SegmentAllocator;Ljava/lang/foreign/MemorySegment;Ljava/lang/foreign/MemorySegment;)I+80 java.base@22.0.2
j  java.lang.invoke.LambdaForm$DMH+0x00007bed570d3400.invokeStaticInit(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)I+14 java.base@22.0.2
j  java.lang.invoke.LambdaForm$MH+0x00007bed570d4c00.invoke(Ljava/lang/Object;Ljava/lang/Object;)I+44 java.base@22.0.2
j  java.lang.invoke.LambdaForm$MH+0x00007bed570d5000.invokeExact_MT(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)I+19 java.base@22.0.2
j  me.bechberger.ebpf.bpf.raw.Lib_1.bpf_object__load(Ljava/lang/foreign/MemorySegment;)I+26
j  me.bechberger.ebpf.bpf.BPFProgram.loadProgram()Ljava/lang/foreign/MemorySegment;+51
j  me.bechberger.ebpf.bpf.BPFProgram.<init>()V+71
j  me.bechberger.ebpf.samples.demo.HelloWorld2.<init>()V+1
j  me.bechberger.ebpf.samples.demo.HelloWorld2Impl.<init>()V+1
j  java.lang.invoke.DirectMethodHandle$Holder.newInvokeSpecial(Ljava/lang/Object;)Ljava/lang/Object;+15 java.base@22.0.2
j  java.lang.invoke.Invokers$Holder.invokeExact_MT(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;+18 java.base@22.0.2
j  jdk.internal.reflect.DirectConstructorHandleAccessor.invokeImpl([Ljava/lang/Object;)Ljava/lang/Object;+40 java.base@22.0.2
j  jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance([Ljava/lang/Object;)Ljava/lang/Object;+60 java.base@22.0.2
j  java.lang.reflect.Constructor.newInstanceWithCaller([Ljava/lang/Object;ZLjava/lang/Class;)Ljava/lang/Object;+41 java.base@22.0.2
j  java.lang.reflect.Constructor.newInstance([Ljava/lang/Object;)Ljava/lang/Object;+30 java.base@22.0.2
j  me.bechberger.ebpf.bpf.BPFProgram.load(Ljava/lang/Class;)Lme/bechberger/ebpf/bpf/BPFProgram;+15
j  me.bechberger.ebpf.samples.demo.HelloWorld2.main([Ljava/lang/String;)V+2
v  ~StubRoutines::call_stub 0x00007bedc0137cc6
V  [libjvm.so+0x8f37db]  JavaCalls::call_helper(JavaValue*, methodHandle const&, JavaCallArguments*, JavaThread*)+0x2db
V  [libjvm.so+0x9a45fe]  jni_invoke_static(JNIEnv_*, JavaValue*, _jobject*, JNICallType, _jmethodID*, JNI_ArgumentPusher*, JavaThread*) [clone .constprop.1]+0x36e
V  [libjvm.so+0x9a6ec8]  jni_CallStaticVoidMethod+0x128
C  [libjli.so+0x3960]  invokeStaticMainWithArgs+0x70
C  [libjli.so+0x4924]  JavaMain+0xd84
C  [libjli.so+0x7ee9]  ThreadJavaMain+0x9
```

OS:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
uname: Linux 6.5.0-41-generic #41~22.04.2-Ubuntu SMP PREEMPT_DYNAMIC Mon Jun  3 11:32:55 UTC 2 x86_64
OS uptime: 0 days 0:46 hours
libc: glibc 2.35 NPTL 2.35

vm_info: OpenJDK 64-Bit Server VM (22.0.2+9-70) for linux-amd64 JRE (22.0.2+9-70), built on 2024-06-04T16:52:23Z by "mach5one" with gcc 13.2.0


I just clone all project for github and run  ./build.sh  and  maven show all success  and   run  ./run.sh demo.HelloWorld2
the jvm show  A fatal error has been detected by the Java Runtime Environment

**Comment by char1st** [comment]
Update libbpf  from 0.5.0 to  1.4.2 . It Works .  Thanks  .
